"""baseline: applications and contacts

The starting point for the schema, matching app/models.py as it stands. The
database this will first run against does not exist yet (KAN-22), so there is
nothing to preserve here — later revisions carry the actual changes.

Two edits were made to what autogenerate produced, because it ran against
SQLite while the deployment target is MySQL:

  * `server_default` uses `sa.func.now()` rather than the literal
    `(CURRENT_TIMESTAMP)` SQLite rendered. func.now() compiles per dialect,
    which is what the models declare.
  * Index creation uses plain `op.create_index` rather than the batch form.
    Batch mode exists to work around SQLite's inability to ALTER in place; it
    is noise in a migration that only creates tables.

Revision ID: de0ac7356ab2
Revises:
Create Date: 2026-08-15 22:48:59.488609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0ac7356ab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('job_link', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('applied', 'phone_screen', 'interview', 'offer', 'rejected', 'ghosted', 'withdrawn', name='applicationstatus'), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_archived_at', 'applications', ['archived_at'], unique=False)
    op.create_index('ix_applications_company', 'applications', ['company'], unique=False)
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_application_id', 'contacts', ['application_id'], unique=False)
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_index('ix_contacts_application_id', table_name='contacts')
    op.drop_table('contacts')

    op.drop_index('ix_applications_id', table_name='applications')
    op.drop_index('ix_applications_company', table_name='applications')
    op.drop_index('ix_applications_archived_at', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
